services:
  cowphone:
    image: nbe95/cowphone:test-os60
    restart: unless-stopped
    ports:
      - 50021:21/tcp
      - 50080:80/tcp
      - 3000-3009:3000-3009/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      OWN_HOST: $OWN_HOST
      CRON_SCHEDULE: $CRON_SCHEDULE
      OS_PHONE_HOST: $OS_PHONE_HOST
      OS_ADMIN_PASSWORD: $OS_ADMIN_PASSWORD
