name: Lint

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  lint:
    name: Lint the typescript code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dev-dependencies
        run: npm install --only=dev
      - name: Run linters
        run: npm run lint

  test:
    name: Test the typescript code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install packages
        run: npm install
      - name: Run unit tests
        run: npm run test

  validate-release:
    name: Validate release label and notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jefflinse/pr-semver-bump@v1.6.0
        name: Bump and tag new version
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major
          minor-label: minor
          patch-label: patch
          noop-labels: ""
          require-release-notes: false
          base-branch: true
          with-v: false
